Merged in new debian package structure for wdb.

diff --git a/debian_files/postrm b/debian_files/postrm
--- a/debian_files/postrm
+++ b/debian_files/postrm
@@ -1,10 +1,8 @@
-#!/bin/sh
+#!/bin/sh -e
 # postrm script for #PACKAGE#
 #
 # see: dh_installdeb(1)
-
-set -e
-
+#
 # summary of how this script can be called:
 #        * <postrm> `remove'
 #        * <postrm> `purge'
@@ -18,27 +16,35 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
+# Source debconf library
 . /usr/share/debconf/confmodule
-if [ -f /usr/share/dbconfig-common/dpkg/postrm.pgsql ]; then
-   . /usr/share/dbconfig-common/dpkg/postrm.pgsql 
-   dbc_go wdb $@
-fi
 
-db_get wdb/database_name && DB_NAME="$RET"
-db_get wdb/user_account && DB_USER="$RET" || DB_USER=wdb
+# Get database information
+db_get wdb/metadata_name && DB_NAME="$RET"
+db_get wdb/metadata_admin && DB_USER="$RET"
 
 case "$1" in
     purge)
-	rm -f /etc/wdb.conf
-	if [ -n "$DB_USER" ]; then
-		echo 'User:$DB_USER is not purged by package. If this user was created by'
-		echo 'the installation, he must be removed manually.'
-	fi
+		# Database purge
+		db_input high wdb/database_removeadmin || true
+		db_go
+		# Uninstall database
+		db_get wdb/database_removeadmin
+		if [ "$RET" = "true" ]; then
+			if [ -n "$DB_USER" ]; then
+	    		deluser --remove-home $DB_USER >> /dev/null || true
+	    		delgroup --only-if-empty $DB_USER >> /dev/null || true
+	    	else
+	    		echo 'WARNING: Could not find the user $DB_USER'
+			fi
+		fi   
+    	# Remove the wdb.conf file.
+		rm -f /etc/wdb.conf
     ;;
 
     upgrade)
-	# Called on old postrm
-	# Nothing to do here; upgrading is handled by the install script
+		# Called on old postrm
+		# Nothing to do here; upgrading is handled by the install script
     ;;
      
     failed-upgrade)
@@ -62,14 +68,13 @@ case "$1" in
     ;;
 
     *)
-        echo "postrm called with unknown argument \`$1'" >&2
+        echo "postrm called with unknown argument '$1'" >&2
         exit 1
     ;;
 esac
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
-
 #DEBHELPER#
 
 exit 0
