various corrections to debian build

diff --git a/debian_files/wdb.postrm b/debian_files/wdb.postrm
--- a/debian_files/wdb.postrm
+++ b/debian_files/wdb.postrm
@@ -19,12 +19,64 @@
 # Source debconf library
 . /usr/share/debconf/confmodule
 
+# Get database information
+db_get wdb/metadata_name && DB_NAME="$RET"
+db_get wdb/metadata_admin && DB_USER="$RET"
+
+case "$1" in
+    purge)
+		# Database purge
+		db_input high wdb/database_removeadmin || true
+		db_go
+		# Uninstall database
+		db_get wdb/database_removeadmin
+		if [ "$RET" = "true" ]; then
+			if [ -n "$DB_USER" ]; then
+	    		deluser --remove-home $DB_USER >> /dev/null || true
+	    		delgroup --only-if-empty $DB_USER >> /dev/null || true
+	    	else
+	    		echo 'WARNING: Could not find the user $DB_USER'
+			fi
+		fi   
+    	# Remove the wdb.conf file.
+		rm -f /etc/wdb.conf
+    ;;
+
+    upgrade)
+		# Called on old postrm
+		# Nothing to do here; upgrading is handled by the install script
+    ;;
+     
+    failed-upgrade)
+		# Called on new postrm
+		# nothing we can do here, so fail
+		false
+		# Fail goes to old preinst: abort-upgrade, and eventually to new 
+		# postrm abort-upgrade
+	;;
+     
+	abort-upgrade)
+	    # Called on new postrm
+	    INSTALLED_VERSION=`su postgres -c "psql $DB_NAME -tc 'SELECT wci.version()' | cut -sd\  -f3"`
+	    OLD_VERSION=`echo $2 | sed s/-.*//`
+	
+	    # If this fails, leaves package in half-installed state.
+	    # otherwise go to old postinst abort-upgrade
+	    test $INSTALLED_VERSION = $OLD_VERSION
+    ;;
+    remove|abort-install|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument '$1'" >&2
+        exit 1
+    ;;
+esac
+
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
 #DEBHELPER#
 
 exit 0
-
-
 
 
